# Generated by Django 5.1.7 on 2025-04-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_clientes_delete_libro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
