# Generated by Django 5.1.7 on 2025-04-05 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_rename_clientes_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El dni debe tener 8 digitos!', regex='^\\d{8}$')]),
        ),
    ]
