# Generated by Django 5.2 on 2025-04-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='notas_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
