# Generated by Django 5.2 on 2025-04-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_producto_notas_tecnicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('por revisar', 'Por revisar'), ('en revision', 'En revisión'), ('presupuestado', 'Presupuestado'), ('aceptado', 'Aceptado'), ('no aceptado', 'No aceptado'), ('esperando repuestos', 'Esperando repuestos'), ('en reparacion', 'En reparación'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=30),
        ),
    ]
